name: to_na_ufam
description: Tô na Ufam

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  page_transition: ^1.1.5
  path_provider: ^1.6.7
  fl_chart: ^0.11.1
  percent_indicator: ^2.1.7+1
  flutter_icons: ^1.1.0
  advance_pdf_viewer: ^1.2.2
  esys_flutter_share: ^1.0.2
  radar_chart: ^1.1.0
  after_layout: ^1.0.7+2
  shared_preferences: ^0.5.12+4
  firebase_admob: ^0.9.3
  firebase_core: 0.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/cursos_ufam.json
    - assets/sexo.json
    - assets/ufam.jpg
    - assets/cursos_ufam_notas.json
    - assets/serie.json
    - assets/tag_colors.json
    - assets/tucano.png
    - assets/psc/provas/PSC2002_1ano_prova.pdf
    - assets/psc/provas/PSC2002_2ano_prova.pdf
    - assets/psc/provas/PSC2002_3ano_prova.pdf
    - assets/psc/provas/PSC2003_1ano_prova.pdf
    - assets/psc/provas/PSC2003_2ano_prova.pdf
    - assets/psc/provas/PSC2003_3ano_prova.pdf
    - assets/psc/provas/PSC2004_1ano_prova.pdf
    - assets/psc/provas/PSC2004_2ano_prova.pdf
    - assets/psc/provas/PSC2004_3ano_prova.pdf
    - assets/psc/provas/PSC2005_1ano_prova.pdf
    - assets/psc/provas/PSC2005_2ano_prova.pdf
    - assets/psc/provas/PSC2005_3ano_prova.pdf
    - assets/psc/provas/PSC2006_1ano_prova.pdf
    - assets/psc/provas/PSC2006_2ano_prova.pdf
    - assets/psc/provas/PSC2006_3ano_prova.pdf
    - assets/psc/provas/PSC2007_1ano_prova.pdf
    - assets/psc/provas/PSC2007_2ano_prova.pdf
    - assets/psc/provas/PSC2007_3ano_prova.pdf
    - assets/psc/provas/PSC2008_1ano_prova.pdf
    - assets/psc/provas/PSC2008_2ano_prova.pdf
    - assets/psc/provas/PSC2008_3ano_prova.pdf
    - assets/psc/provas/PSC2009_1ano_prova.pdf
    - assets/psc/provas/PSC2009_2ano_prova.pdf
    - assets/psc/provas/PSC2009_3ano_prova.pdf
    - assets/psc/provas/PSC2010_1ano_prova.pdf
    - assets/psc/provas/PSC2010_2ano_prova.pdf
    - assets/psc/provas/PSC2010_3ano_prova.pdf
    - assets/psc/provas/PSC2011_1ano_prova.pdf
    - assets/psc/provas/PSC2011_2ano_prova.pdf
    - assets/psc/provas/PSC2011_3ano_prova.pdf
    - assets/psc/provas/PSC2012_1ano_prova.pdf
    - assets/psc/provas/PSC2012_2ano_prova.pdf
    - assets/psc/provas/PSC2012_3ano_prova.pdf
    - assets/psc/provas/PSC2013_1ano_prova.pdf
    - assets/psc/provas/PSC2013_2ano_prova.pdf
    - assets/psc/provas/PSC2013_3ano_prova.pdf
    - assets/psc/provas/PSC2014_1ano_prova.pdf
    - assets/psc/provas/PSC2014_2ano_prova.pdf
    - assets/psc/provas/PSC2014_3ano_prova.pdf
    - assets/psc/provas/PSC2015_1ano_prova.pdf
    - assets/psc/provas/PSC2015_2ano_prova.pdf
    - assets/psc/provas/PSC2015_3ano_prova.pdf
    - assets/psc/provas/PSC2016_1ano_prova.pdf
    - assets/psc/provas/PSC2016_2ano_prova.pdf
    - assets/psc/provas/PSC2016_3ano_prova.pdf
    - assets/psc/provas/PSC2017_1ano_prova.pdf
    - assets/psc/provas/PSC2017_2ano_prova.pdf
    - assets/psc/provas/PSC2017_3ano_prova.pdf
    - assets/psc/provas/PSC2018_1ano_prova.pdf
    - assets/psc/provas/PSC2018_2ano_prova.pdf
    - assets/psc/provas/PSC2018_3ano_prova.pdf
    - assets/psc/provas/PSC2019_1ano_prova.pdf
    - assets/psc/provas/PSC2019_2ano_prova.pdf
    - assets/psc/provas/PSC2019_3ano_prova.pdf
    - assets/psc/provas/PSC2020_1ano_prova.pdf
    - assets/psc/provas/PSC2020_2ano_prova.pdf
    - assets/psc/provas/PSC2020_3ano_prova.pdf
    - assets/psc/gabaritos/PSC2002_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2002_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2002_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2003_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2003_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2003_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2004_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2004_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2004_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2005_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2005_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2005_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2006_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2006_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2006_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2007_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2007_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2007_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2008_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2008_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2008_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2009_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2009_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2009_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2010_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2010_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2010_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2011_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2011_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2011_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2012_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2012_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2012_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2013_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2013_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2013_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2014_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2014_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2014_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2015_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2015_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2015_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2016_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2016_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2016_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2017_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2017_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2017_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2018_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2018_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2018_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2019_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2019_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2019_3ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2020_1ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2020_2ano_gabarito.pdf
    - assets/psc/gabaritos/PSC2020_3ano_gabarito.pdf
    - assets/assuntos/1ano/bio1.json
    - assets/assuntos/1ano/fis1.json
    - assets/assuntos/1ano/geo1.json
    - assets/assuntos/1ano/hist1.json
    - assets/assuntos/1ano/lit1.json
    - assets/assuntos/1ano/mat1.json
    - assets/assuntos/1ano/port1.json
    - assets/assuntos/1ano/quim1.json
    - assets/assuntos/2ano/bio2.json
    - assets/assuntos/2ano/fis2.json
    - assets/assuntos/2ano/geo2.json
    - assets/assuntos/2ano/hist2.json
    - assets/assuntos/2ano/lit2.json
    - assets/assuntos/2ano/mat2.json
    - assets/assuntos/2ano/port2.json
    - assets/assuntos/2ano/quim2.json
    - assets/assuntos/3ano/bio3.json
    - assets/assuntos/3ano/fis3.json
    - assets/assuntos/3ano/geo3.json
    - assets/assuntos/3ano/hist3.json
    - assets/assuntos/3ano/lit3.json
    - assets/assuntos/3ano/mat3.json
    - assets/assuntos/3ano/port3.json
    - assets/assuntos/3ano/quim3.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
